spring:
  application:
    name: cart-service

  config:
    import: optional:configserver:http://localhost:8888

# redis:
#   host: localhost
#   port: 6379
#
cors:
  allowed-origins: http://localhost:5173

# server:
#   port: 8087 
